### ISSUE TITLE
Getting TypeError: expected string or buffer

### ISSUE THREAD

**Issue by marcinrosner** [bmcfee/muda#66]
Hello,
I installed muda 0.2.0 successfully, but when I import it I get the following error:
>>> import muda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/muda/__init__.py", line 5, in <module>
    from . import deformers
  File "/usr/local/lib/python2.7/dist-packages/muda/deformers/__init__.py", line 7, in <module>
    from .pitch import *
  File "/usr/local/lib/python2.7/dist-packages/muda/deformers/pitch.py", line 6, in <module>
    import librosa
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/usr/local/lib/python2.7/dist-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/usr/local/lib/python2.7/dist-packages/joblib/memory.py", line 847, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer

How can I fix it?

**Comment by marcinrosner** [comment]
I have just found a solution, it refers to the following post:
https://github.com/librosa/librosa/issues/732
